#18 Edge Evaluator
Inbibo/adonisfx_docs pull request #28
Opened 2024-02-22 09:14 UTC by luisalbaceteinbibo

### Description of this issue
Edge evaluator node documented.

### Pages to review
- `edge_evaluator.md`

Issue of this PR: #18

2024-02-23 16:29 UTC, lucasferryinbibo requested changes
One small comment on my end

2024-02-23 16:29 UTC, lucasferryinbibo commented on docs/documentation/maya/edge_evaluator.md
> +The AdnEdgeEvaluator node is a dependency node that computes deformation changes in edges. Based on two input meshes it will output a compression map of the edges.
We should maybe add an image with the result of the edhe evaluator and maybe an example of how to use or connect it to out deformers

2024-02-24 15:12 UTC, lucasferryinbibo commented on docs/documentation/maya/edge_evaluator.md
> +The AdnEdgeEvaluator node is a dependency node that computes deformation changes in edges. Based on two input meshes it will output a compression map of the edges.
I don't have the resources at the moment to provide that screenshot. I'm approving this PR given its current status

2024-02-24 15:17 UTC, lucasferryinbibo approved these changes

2024-02-26 14:29 UTC, josevalverdeinbibo approved these changes
Great job! Just one comment to check.

2024-02-26 14:29 UTC, josevalverdeinbibo commented on docs/documentation/maya/edge_evaluator.md
> +  - <b class="mesh_color"> Deform Mesh (D):</b> Mesh with deformations in its geometry. These deformations are not generated by the animation of a rig.
```suggestion
  - **Rest Mesh (R)**: Mesh with no deformation or animation.
  - **Deform Mesh (D)**: Mesh with deformations in its geometry. These deformations are not generated by the animation of a rig.

```

2024-02-26 14:31 UTC, josevalverdeinbibo commented on docs/documentation/maya/edge_evaluator.md
> +  - <b class="mesh_color"> Deform Mesh (D):</b> Mesh with deformations in its geometry. These deformations are not generated by the animation of a rig.
Done.

2024-02-27 08:52 UTC, carlosmonteagudoinbibo approved these changes

2024-02-27 08:53 UTC, merged