#19 Maya v1.0.0 Tools docs
Inbibo/adonisfx_docs pull request #34
Opened 2024-02-22 18:17 UTC by lucasferryinbibo

# Description of this issue
Tools documented.

# Pages to review
tools.md

Issue of this PR: https://github.com/Inbibo/adonisfx_docs/issues/19

2024-02-24 17:16 UTC, lucasferryinbibo reviewed
I've left a comment to update some screenshots

2024-02-24 17:16 UTC, lucasferryinbibo commented on docs/documentation/maya/tools.md
> +  <figcaption> Figure 6: AdonisFX paint tool displaying the paintable attributes of the deformer. </figcaption>
Update screenshot with Global Damping showing in the list after update

2024-02-24 17:16 UTC, lucasferryinbibo commented on docs/documentation/maya/tools.md
> +  <figcaption> Figure 8: Paintable attributes listed in the UI for an AdnSkin deformer. </figcaption>
Update screenshot with Global Damping showing in the list after update

2024-02-26 14:59 UTC, josevalverdeinbibo requested changes
Great job! Some comments to check.

2024-02-26 14:59 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +  <figcaption>Figure 1: AdonisFX Import Tool UI</figcaption>
Add bold style to all "Figure x":
```suggestion
  <figcaption><b>Figure 1</b>: AdonisFX Import Tool UI</figcaption>
```

2024-02-26 14:59 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +2. Select, using the checkboxes, the deformers and the individual settings to export to the AAD file. For example selecting "Maps" and "Attachments" would export the painted attribute maps and the ma
```suggestion
2. Select, using the checkboxes, the deformers and the individual settings to export to the AAD file. For example selecting *Maps* and *Attachments* would export the painted attribute maps and the matrices for the attachments relative to an AdnMuscle or AdnRibbonMuscle deformer.
```

2024-02-26 15:02 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +  <figcaption>Figure 1: AdonisFX Import Tool UI</figcaption>
Done.

2024-02-26 15:03 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +7. The assignments can then be imported using the **Import* button or everything can be cleared using the *Clear All* button.
Done.

2024-02-26 15:03 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +2. Select, using the checkboxes, the deformers and the individual settings to export to the AAD file. For example selecting "Maps" and "Attachments" would export the painted attribute maps and the ma
Done.

2024-02-26 15:04 UTC, josevalverdeinbibo commented on docs/documentation/maya/tools.md
> +For Source elements (sensors) press the *Reload Left** button and for Destination elements (deformers) press the *Reload Right* button.
Done.

2024-02-27 09:03 UTC, carlosmonteagudoinbibo approved these changes

2024-02-27 09:03 UTC, merged